### ISSUE TITLE
S3 Bucket depends_on 

### ISSUE THREAD

**Issue by methridge** [hashicorp-services/enablement-terraform-lab-modules#2]
https://github.com/hashicorp-services/enablement-terraform-lab-modules/blob/a177d128e47ee3e806c54086272680d3494b9f8a/lab-tfc-private-module-registry/terraform-aws-acdmy-webapp/main.tf#L2

The new depends_on for the S3 bucket caused the following error in today's class.

│ Error: Cycle: module.acdmy-webapp.aws_s3_bucket_ownership_controls.bucket, module.acdmy-webapp.aws_s3_bucket_public_access_block.bucket, module.acdmy-webapp.aws_s3_bucket_acl.bucket, module.acdmy-webapp.aws_s3_bucket.bucket

Lab is using:
root@terraform:/home/terraform# terraform version
Terraform v1.3.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.67.0
+ provider registry.terraform.io/hashicorp/tls v4.0.4

**Comment by amarrone-hashicorp** [comment]
This issue should be fixed based on Mike Guy's fix from above. 

If the issue persists feel free to re-open the issue and we will take a look again.
