### ISSUE TITLE
Minor - outdated screenshot in https://play.instruqt.com/HashiCorp-EA/tracks/tfc-creating-a-new-account/challenges/create-training-account/assignment 

### ISSUE THREAD

**Issue by ghost** [hashicorp-services/enablement-terraform-lab-modules#4]
**Describe the bug**
The screenshot used in the lab doesn't say "try an example configuration" anymore. Minor and obviously not rocket science to work out what should be used, but ideal to be updated.

**Old Screenshot Seen in Lab**
Screenshot seen in the Instruqt notes shown below:

![image](https://github.com/hashicorp-services/enablement-terraform-lab-modules/assets/103026065/ad214882-c028-4da8-b694-4876e18d4ba7)

**Actual Screen in TFC**
Actual image that should be used...

![image](https://github.com/hashicorp-services/enablement-terraform-lab-modules/assets/103026065/afa414fe-5e11-4d34-ad29-5c1ab7c58d6b)

**Comment by amarrone-hashicorp** [comment]
[Moved to Terraform Instruqt Issue 163](https://github.com/hashicorp-services/enablement-terraform-instruqt/issues/163)
