### ISSUE TITLE
Cost estimation not enabled, but slides refer to it - https://play.instruqt.com/HashiCorp-EA/tracks/tfc-workflows-api/challenges/api-driven-workflow/assignment

### ISSUE THREAD

**Issue by ghost** [hashicorp-services/enablement-terraform-lab-modules#5]
**Describe the bug**
The instruqt instructions say “once the run status reaches cost estimated, click on the run” - but cost estimation is not enabled.

**To Fix**
Either...

1. Enable cost estimation for the org (preferred) during setup.
2. Change the wording so it doesn't refer to cost estimation.

**Comment by amarrone-hashicorp** [comment]
[Moved to Terraform Instruqt Issue 163](https://github.com/hashicorp-services/enablement-terraform-instruqt/issues/163)
