### ISSUE TITLE
Wording related to import is misleading - https://play.instruqt.com/HashiCorp-EA/tracks/tfc-sentinel/challenges/sentinel-policy-setup/assignment

### ISSUE THREAD

**Issue by ghost** [hashicorp-services/enablement-terraform-lab-modules#6]
**Describe the bug**
In the instructions it talks the student through the various parts of the policy. With regards to the import of tfplan/v2 it says...

"The first section is a simple import statement to allow the import of any mock data. In this lab we are not using mock data, but when writing Sentinel policies for your own environment it is a good idea to use the mock data from previous runs to test the policy. This helps to ensure policies are checking the correct values, and behaving as expected."

This isn't just used for mock data so is confusing. The import statement provides easy access to the plan and is not specific to just mocking, which the wording alludes to.

https://developer.hashicorp.com/terraform/cloud-docs/policy-enforcement/sentinel/import/tfplan-v2

**Comment by amarrone-hashicorp** [comment]
[Moved to Terraform Instruqt Issue 163](https://github.com/hashicorp-services/enablement-terraform-instruqt/issues/163)
