### ISSUE TITLE
Markdown syntax rendering through to student in Instruqt - https://play.instruqt.com/HashiCorp-EA/tracks/tfc-sentinel/challenges/sentinel-policy-setup/assignment

### ISSUE THREAD

**Issue by ghost** [hashicorp-services/enablement-terraform-lab-modules#7]
**Describe the bug**
In the lab https://play.instruqt.com/HashiCorp-EA/tracks/tfc-sentinel/challenges/sentinel-policy-setup/assignment there is a section where the markdown has been messed up and the user see's it rendering through to them...

Within the code block, you see the following verbatim...

![image](https://github.com/hashicorp-services/enablement-terraform-lab-modules/assets/103026065/95092788-fd88-4e47-8b40-34264562b356)

**Comment by amarrone-hashicorp** [comment]
[Moved to Terraform Instruqt Issue 163](https://github.com/hashicorp-services/enablement-terraform-instruqt/issues/163)
